collections:
    - bugs

exclude:
    - "README.md"
    - "LICENSE.md"

baseurl: "http://brendanzagaeski.github.io/bug-annotations/"

#defaults:
#    - scope:
#        path: ""
#        type: my_collection
#    values:
#        layout: bug
