collections:
    - bugs

exclude:
    - "README.md"
    - "LICENSE.md"
    - "bugs/_template.md"

baseurl: "/bug-annotations"

#defaults:
#    - scope:
#        path: ""
#        type: my_collection
#    values:
#        layout: bug
